### ISSUE TITLE
Cite this repo?

### ISSUE THREAD

**Issue by semantic-nomad** [Vocamp/Virtual-Hackahon-on-Glacier-topic#25]
This work may be referenced in future publications. It may be easier to do so if there is a `citation.cff` file.  For this repository, it would look something like this:

```
cff-version: 1.2.0
message: "If you use this resource, please cite as below."
authors:
- family-names: "Berg-Cross"
  given-names: "Gary"
  orcid: ""
- family-names: "Buttigieg "
  given-names: "Pier"
  orcid: ""
- family-names: "Whitehead"
  given-names: "Brandon"
  orcid: ""
- family-names: "Singh Khalsa"
  given-names: "Siri Jodha"
  orcid: ""
- family-names: "Blumberg"
  given-names: "Kai"
  orcid: ""
- family-names: "Duerr"
  given-names: "Ruth"
  orcid: ""
- family-names: "Varanka"
  given-names: "Dalia"
  orcid: ""
- family-names: "Arundel"
  given-names: "Samantha"
  orcid: ""
- family-names: "Wiegand"
  given-names: "Nancy"
  orcid: ""
- family-names: "Hahmann"
  given-names: "Torsten"
  orcid: ""
- family-names: "Brodaric"
  given-names: "Boyan"
  orcid: ""
- family-names: "Sinha"
  given-names: "Gaurav"
  orcid: ""
- family-names: "Vardeman II"
  given-names: "Charles F."
  orcid: ""
- family-names: "Schildhauer"
  given-names: "Mark"
  orcid: ""
- family-names: "Chong"
  given-names: "Steven"
  orcid: ""
title: "Glacier VoCamp virtual hackathon documents"
#doi: 
date-released: 2018-02-02
url: "https://github.com/Vocamp/Virtual-Hackahon-on-Glacier-topic"
type: generic
```

Participants list copied from initial meeting here:
https://docs.google.com/document/d/1YcVHJdFfdO4QdkcHNx4eBt9-W3A2DC4i-8RW0Zxr0XA/edit

We would need everyone's agreement, and ORCID.  @Garybc what do you think about adding this file?
